name: CI - Unit + API + UI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-and-api:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports: [ "27017:27017" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run unit tests
        working-directory: backend
        run: npm test

      - name: Start backend
        working-directory: backend
        env:
          PORT: 4000
          JWT_SECRET: testsecret
          MONGODB_URI: mongodb://127.0.0.1:27017/taskmgr_ci
        run: |
          nohup npm start >/tmp/server.log 2>&1 &
          sleep 5

      - name: Run API tests (Newman)
        run: npx newman run backend/postman_collection.json -e backend/postman_env.json --env-var baseUrl=http://127.0.0.1:4000

  ui-tests:
    runs-on: ubuntu-latest
    needs: unit-and-api
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Run UI tests headless
        working-directory: backend
        env:
          HEADLESS: 1
          UI_BASE: http://127.0.0.1:8080
        run: npm run ui
